Print the error to stderr where it can actually be seen

diff --git a/shims/npm b/shims/npm
--- a/shims/npm
+++ b/shims/npm
@@ -81,8 +81,8 @@ resolve_canon_npm() {
   npm_location="${ASDF_NODEJS_CANON_NPM_PATH:-$(search_npm_on_current_path || manually_search_npm_bin)}"
 
   if ! [ "$npm_location" ]; then
-    printf "asdf-nodejs couldn't find a suitable npm executable\n"
-    printf "This is probably a problem with the plugin, please report this issue at https://github.com/asdf-vm/asdf-nodejs/issues\n"
+    printf "asdf-nodejs couldn't find a suitable npm executable\n" >&2
+    printf "This is probably a problem with the plugin, please report this issue at https://github.com/asdf-vm/asdf-nodejs/issues\n" >&2
     exit 1
   fi
 
